### PR TITLE
Refactor Help .html to .schelp

### PR DESCRIPTION
**Pull request by joslloand**
Issue https://github.com/supercollider-quarks/MathLib/issues/8, refactor Help .html to .schelp

Additional formatting issues for .schelp files:

- add links to new MathLib.schelp splash page
- add Libraries/MathLib documentation category
- conform .schelp style, adding **Authors**, where appropriate

---
**List of changes:**

Remove: html for SpherCoords
Help found in html already available as schelp.

Refactor: Help Bessel
add: Bessel.schelp
Update: include BOOST examples for Bessel

Refactor: Help GenLaguerre
add: GenLaguerre.schelp

Refactor: Help LaTeX
add: LaTeX.schelp
Note: minimally documented!
Update: Latex.schelp, add MathLib quark link

Refactor: Help Matrix
edit: Matrix.schelp
Update: Matrix, correct Array class links

Refactor: Pboolnet
add: Pboolnet.schelp
Update: PBoolnet, add credits
Fix: PBoolnet, remove incorrect credit link

Update: Matrix, name Bovermann
Update: Cartesian, Spherical remove email address.

Refactor: Help Polynomial
add: Polynomial.schelp

Refactor Pperform & Preduce Help
add: Pperform.schelp, Preduce.schelp

Update: Polynomial, Pperform, Preduce Help
Include “part of MathLib”

Refactor: Help Quaternion
add: Quaternion.schelp

Refactor: ScatterView Help
add: ScatterView.schelp, ScatterView2.schelp, ScatterView3d.schelp
NOTE: these classes appear to have further dependencies and / or use deprecated classes or methods

Refactor: Trafo Help
add: Trafo.schelp

Refactor: Solver Help
add: Euler.schelp, NFunc.schelp, RK2.schelp, RK3.schelp, RK4.schelp, Solver.schelp, SystemNFunc.schelp

Refactor: MarkovSet Help
add: FuzzyDictionary.schelp, FuzzySet.schelp, MarkovSet.schelp, MarkovSetN.schelp, ShannonFinger.schelp, ShannonSet.schelp, supermarkov_example.schelp

Refactor: exStatistics Help
add: exStatistics.schelp

Refactor: rewriteString Help
add: rewriteString.schelp

Refactor: MathLib Help
add: MathLib.schelp
update: add link back for each documented class to MathLib spalsh page.
update: add MathLib category links

Include a README noting HTML files for help are deprecated since SC 3.5.

### CODE REVIEW

**Comment by telephon** [comment]
Just an idea: what about moving the html to a folder, just in case some people still rely on it somehow? And also just in case we realise something got missing? I did look through your changes - again, thanks a lot - but I didn't have the time to check if every information was still there in the new version.

**Comment by joslloand** [comment]
I think the reason I'd decided to just remove all this was that (I believe) some documentation was as `schelp`, some  as `html` and then there was some as both. I'd felt that part of the clean up should be to actually remove all the `html` so as not to offer any confusion.

I'll go ahead and put the `html` back and include a short README stating that `html` documentation should be regarded as deprecated.

I did make an effort to preserve all information... but as you say, keeping the `html` gives us the opportunity to be sure.

**Comment by joslloand** [comment]
> Remove: html for SpherCoords
> Help found in html already available as schelp

Ah... having a quick review... as I'm the author of SpherCoords, I won't replace those `html` help files.

**Comment by telephon** [comment]
ah good to know :)
why do you need SystemOverwrites in SpherCoords? There seem to be many methods in there that do not overwrite anything.

In general, I'd find it good if we could avoid overwriting if possible.

**Comment by telephon** [comment]
Ah I see, it is only `@` which actually overwrites something. `@` seems like a convenience, could we maybe live without it? It could be an optional thing, perhaps?

**Comment by joslloand** [comment]
Just pushed the update restoring the old HTMLs.

**Comment by joslloand** [comment]
> Ah I see, it is only @ which actually overwrites something. @ seems like a convenience, could we maybe live without it? It could be an optional thing, perhaps?

Funny you mention this, actually. When I was having a _very brief_ look, I did have a similar thought wondering about the overwrites, myself. 

SpherCords is used by the ATK. I'd have to do some snooping to see if we're actually using the `@` overwrite.

Maybe the thing to do is to file an issue against overwrites found in the SpherCords classes, and I can have a look and a think when I get some more time?

**Comment by telephon** [comment]
> Maybe the thing to do is to file an issue against overwrites found in the SpherCords classes, and I can have a look and a think when I get some more time?

OK, makes sense!

**Comment by telephon** [comment]
Is this all ready to merge?

**Comment by joslloand** [comment]
Everything should be all set to go!

(Apologies for the late reply... have been away in [New Mexico](https://en.wikipedia.org/wiki/New_Mexico) for the past week...)

**Comment by telephon** [comment]
> (Apologies for the late reply... have been away in [New Mexico](https://en.wikipedia.org/wiki/New_Mexico) for the past week...)

Great - DF is one of the most interesting places!

**Pull request merged**
